version: "3.9"
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

  api:
    build: .              # <— build from server/database/Dockerfile
    image: nodeapp        # optional tag
    ports:
      - "3030:3030"
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}
